# Generated by Django 3.1.7 on 2021-03-24 06:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_auto_20210324_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='mobile_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$')]),
        ),
    ]
