# Generated by Django 3.1.7 on 2021-03-26 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0005_userregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='demoapp.userregister'),
            preserve_default=False,
        ),
    ]
